### ISSUE TITLE
python main.py have error.

### ISSUE THREAD

**Issue by sepzfq** [WangShaoSUN/grasp-transformer#1]
Hello, Mr. Wang. Thank you for your code sharing.
I have a questions that confuse me:
when I run main.py, it have error " 'Namespace‘ object has no attribute ‘vis‘ ".
So I checked “ gg_cnn”，find the main.py don't have " parser.add_argument('--vis', action='store_true', help='Visualise the training process')  ".   
After I added it, I found it was working normally.But when running in this way, the output models are always “ epoch_XX_iou_0 ”, and every epoches runs very fast.
I wonder if some of my parameters are not set, resulting in no training.
I hope you can take the time to answer my confusion. Thanlk you very much!!!!
In addition, I noticed that you are Chinese. This is my wechat17638091261.
I really hope we can have further communication,
Finally, praise your scientific research spirit

**Comment by WangShaoSUN** [comment]
@sepzfq I have updated the code, please download the code and re-run it.

**Comment by sepzfq** [comment]
Problem had solved.Thanks for your generous answer！
