### ISSUE TITLE
test or visualization

### ISSUE THREAD

**Issue by sepzfq** [WangShaoSUN/grasp-transformer#2]
Hello,Mr.Wang
I would like to know after the model is generated, is there a test or visualization phase for this project?
Looking forward to your answer.

**Comment by WangShaoSUN** [comment]
Hi sepzfq:

I have updated some visualize  demos. Hope it can help you。

**Comment by houph4** [comment]
Thanks for @WangShaoSUN @sepzfq .I had finished the work of visualization based on the latest changed files.
