### ISSUE TITLE
running a robot

### ISSUE THREAD

**Issue by yoon-dongmin** [WangShaoSUN/grasp-transformer#3]
Hello, it is very nice work, and inspired my work.
I want to apply this model to our panda robot, but I could't find the files.
So, could you share your panda simulation files? It will be exactly help me a lot.

**Comment by WangShaoSUN** [comment]
Sorry, due to some issues with the previous code, we have temporarily removed it. We will update a more complete version in the future.   Our previous code for real panda Franka was referenced from this repository （https://github.com/dougsm/mvp_grasp).
