### ISSUE TITLE
Running on a Robot of ROS implementation for running the grasping system?

### ISSUE THREAD

**Issue by ZJU-PLP** [WangShaoSUN/grasp-transformer#5]
@WangShaoSUN 

Hi, dear Shaochen:

I cannot open the link when to reproduce the experiment on a robot provided by your link.

![image](https://user-images.githubusercontent.com/32757213/195853801-1eb8b4d9-a645-4249-954b-634587c56477.png)

![image](https://user-images.githubusercontent.com/32757213/195853147-4a47cf1d-40cb-436d-9a8b-5a8ce13dc3bc.png)

**Comment by WangShaoSUN** [comment]
You can refer to https://github.com/dougsm/ggcnn_kinova_grasping.
