### ISSUE TITLE
关于grasp 1b评价指标的问题

### ISSUE THREAD

**Issue by meiguiz** [WangShaoSUN/grasp-transformer#6]
师兄，有没有你在grasp 1b上的结果？那个评估是按照最高得分抓取框评价，还是说top number 评价，还是说得分高于多少的全部评价？

**Comment by WangShaoSUN** [comment]
评估是根据质量最高的抓取框进行评价的

**Comment by meiguiz** [comment]
那师兄的准确率是多少能说一下吗在test_seen和novel上？感谢！！！

**Comment by WangShaoSUN** [comment]
在arxiv上，论文的附录里有说
